name: Auto Tag and Release

on:
  push:
    branches:
      - main
      - master

# 添加权限配置
permissions:
  contents: write

jobs:
  auto-tag-and-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Check if commit message contains @CHANGELOG.md
        id: check-commit
        run: |
          COMMIT_MSG=$(git log --format=%B -n 1 HEAD)
          if echo "$COMMIT_MSG" | grep -q "@CHANGELOG.md"; then
            echo "skip=true" >> $GITHUB_OUTPUT
          else
            echo "skip=false" >> $GITHUB_OUTPUT
          fi

      - name: Get commit message
        if: steps.check-commit.outputs.skip == 'false'
        id: commit-info
        run: |
          COMMIT_MSG=$(git log --format=%B -n 1 HEAD)
          # 使用更安全的转义方法，避免GitHub Actions解析错误
          COMMIT_MSG_ESCAPED=$(echo "$COMMIT_MSG" | sed 's/%/%25/g' | sed 's/\r/%0D/g' | sed 's/\n/%0A/g')
          echo "message<<EOF" >> $GITHUB_OUTPUT
          echo "$COMMIT_MSG_ESCAPED" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT
          
          # 获取提交作者
          COMMIT_AUTHOR=$(git log --format=%an -n 1 HEAD)
          COMMIT_AUTHOR_ESCAPED=$(echo "$COMMIT_AUTHOR" | sed 's/%/%25/g' | sed 's/\r/%0D/g' | sed 's/\n/%0A/g')
          echo "author<<EOF" >> $GITHUB_OUTPUT
          echo "$COMMIT_AUTHOR_ESCAPED" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT
          
          # 获取提交时间
          COMMIT_DATE=$(git log --format=%ad --date=iso -n 1 HEAD)
          COMMIT_DATE_ESCAPED=$(echo "$COMMIT_DATE" | sed 's/%/%25/g' | sed 's/\r/%0D/g' | sed 's/\n/%0A/g')
          echo "date<<EOF" >> $GITHUB_OUTPUT
          echo "$COMMIT_DATE_ESCAPED" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Create and push tag
        if: steps.check-commit.outputs.skip == 'false'
        id: create-tag
        run: |
          # 运行标签创建脚本
          node scripts/create-tag.js

      - name: Create Release
        if: steps.check-commit.outputs.skip == 'false'
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ steps.create-tag.outputs.version }}
          name: ${{ steps.create-tag.outputs.version }}
          body: |
            # Release ${{ steps.create-tag.outputs.version }}
            
            ## 提交信息
            
            ${{ steps.commit-info.outputs.message }}
            
            ## 提交详情
            
            - 作者: ${{ steps.commit-info.outputs.author }}
            - 时间: ${{ steps.commit-info.outputs.date }}
            
            ---
            
            自动发布于 $(date +'%Y-%m-%d %H:%M:%S')
          draft: false
          prerelease: false
          makeLatest: true