name: Auto Tag and Release

on:
  push:
    branches:
      - main
      - master

jobs:
  auto-tag-and-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Check if commit message contains @CHANGELOG.md
        id: check-commit
        run: |
          COMMIT_MSG=$(git log --format=%B -n 1 HEAD)
          if echo "$COMMIT_MSG" | grep -q "@CHANGELOG.md"; then
            echo "skip=true" >> $GITHUB_OUTPUT
          else
            echo "skip=false" >> $GITHUB_OUTPUT
          fi

      - name: Create and push tag
        if: steps.check-commit.outputs.skip == 'false'
        id: create-tag
        run: |
          # 运行标签创建脚本
          node scripts/create-tag.js
          
          # 获取版本号
          VERSION=$(grep -m 1 "### v" CHANGELOG.md | sed -E 's/### (v[0-9.]+).*/\1/')
          echo "version=$VERSION" >> $GITHUB_OUTPUT
          
          # 提取更新日志
          echo "release_notes<<EOF" >> $GITHUB_OUTPUT
          awk '/^### v'"$VERSION"'/,/^### v/ { if (!/^### v'"$VERSION"'/ && !/^### v/) print }' CHANGELOG.md | head -n -1 >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Create Release
        if: steps.check-commit.outputs.skip == 'false'
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.create-tag.outputs.version }}
          release_name: ${{ steps.create-tag.outputs.version }}
          body: |
            # Release ${{ steps.create-tag.outputs.version }}
            
            ## 更新内容
            
            ${{ steps.create-tag.outputs.release_notes }}
            
            ---
            
            自动发布于 $(date +'%Y-%m-%d %H:%M:%S')
          draft: false
          prerelease: false