name: Bump version

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'VERSION.txt'
      - 'CHANGELOG.md'
  workflow_dispatch:

jobs:
  bump-version:
    if: github.repository == 'LibreSpark/LibreTV'
    runs-on: ubuntu-latest
    env:
      TZ: 'Asia/Shanghai'

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Bump version
      run: |
        CURRENT_TIME=$(date +"%Y-%m-%d %H:%M")
        VERSION=$(date +"%Y%m%d%H%M")
        git config user.name 'github-actions[bot]'
        git config user.email 'github-actions[bot]@users.noreply.github.com'
        
        # 更新VERSION.txt
        echo $VERSION > VERSION.txt
        
        # 添加并提交更改
        git add VERSION.txt
        git commit -m "Auto Update version to $VERSION"
        git push origin main

    - name: Delete workflow runs
      uses: Mattraks/delete-workflow-runs@main
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        repository: ${{ github.repository }}
        retain_days: 0
        keep_minimum_runs: 2